version: '3.1'

services:
  bot:
    build:
      context: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - API=${API}
      - URL=${URL}
      - COORDINATES=${COORDINATE}
      - ADMIN_ID=${ADMIN_ID}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
     image: adminer
     restart: always
     ports:
       - "8080:8080"

volumes:
  postgres-data:



